[project]
name = "lmp-anly"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib",
    "numpy",
    "pandas",
    "rtoml",
    "scipy",
    "typer",
    "typing-extensions>=4.15.0",
]
classifiers = ["Private :: Do Not Upload"]
[project.scripts]
lmp-anly = "lmp_anly.__main__:main"
