[project]
name = "lmp-anly"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib",
    "numpy<2.0.0",
    "pandas",
    "rtoml",
    "scipy==1.13.1",
    "typer",
]
classifiers = ["Private :: Do Not Upload"]
[project.scripts]
lmp-anly = "lmp_anly.__main__:main"
