name: Build and Release

on:
  push:
    tags:
      - 'v*' # 当你推送以 v 开头的标签（如 v1.0.1）时触发

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # 同时在三个系统上运行
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        if: matrix.os != 'ubuntu-latest'
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        if: matrix.os != 'ubuntu-latest'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies and Build
        if: matrix.os != 'ubuntu-latest'
        run: |
          uv venv --python 3.11
          uv pip install --system . pyinstaller
          uv run pyinstaller --onefile --name lmp-anly-${{ matrix.os }} src/lmp_anly/__main__.py

      - name: Build executable on manylinux
        if: matrix.os == 'ubuntu-latest'
        run : |
          docker run --rm -v "${{github.workspace}}:/src" -w /src quay.io/pypa/manylinux2014_x86_64 bash -c '
          set -e

          yum install -y curl
          curl -LsSf https://astral.sh/uv/install.sh | sh
          export PATH="$HOME/.local/bin:$PATH"
          uv pip install --no-build --python /opt/python/cp311-cp311/bin/python . pyinstaller 
          uv run --python /opt/python/cp311-cp311/bin/python pyinstaller --onefile --name lmp-anly-${{matrix.os}} src/lmp_anly/__main__.py
          '

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}
          path: |
            dist/lmp-anly-*
            dist/*.exe

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            binary-ubuntu-latest/*
            binary-windows-latest/*
            binary-macos-latest/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
